// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: blockio/gcp.proto

package blockio

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mode          uint32                 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReq) Reset() {
	*x = CreateReq{}
	mi := &file_blockio_gcp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReq) ProtoMessage() {}

func (x *CreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_blockio_gcp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReq.ProtoReflect.Descriptor instead.
func (*CreateReq) Descriptor() ([]byte, []int) {
	return file_blockio_gcp_proto_rawDescGZIP(), []int{0}
}

func (x *CreateReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CreateReq) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type CreateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRes) Reset() {
	*x = CreateRes{}
	mi := &file_blockio_gcp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRes) ProtoMessage() {}

func (x *CreateRes) ProtoReflect() protoreflect.Message {
	mi := &file_blockio_gcp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRes.ProtoReflect.Descriptor instead.
func (*CreateRes) Descriptor() ([]byte, []int) {
	return file_blockio_gcp_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type WriteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteReq) Reset() {
	*x = WriteReq{}
	mi := &file_blockio_gcp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteReq) ProtoMessage() {}

func (x *WriteReq) ProtoReflect() protoreflect.Message {
	mi := &file_blockio_gcp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteReq.ProtoReflect.Descriptor instead.
func (*WriteReq) Descriptor() ([]byte, []int) {
	return file_blockio_gcp_proto_rawDescGZIP(), []int{2}
}

func (x *WriteReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteReq) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *WriteReq) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	N             int32                  `protobuf:"varint,2,opt,name=n,proto3" json:"n,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRes) Reset() {
	*x = WriteRes{}
	mi := &file_blockio_gcp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRes) ProtoMessage() {}

func (x *WriteRes) ProtoReflect() protoreflect.Message {
	mi := &file_blockio_gcp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRes.ProtoReflect.Descriptor instead.
func (*WriteRes) Descriptor() ([]byte, []int) {
	return file_blockio_gcp_proto_rawDescGZIP(), []int{3}
}

func (x *WriteRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WriteRes) GetN() int32 {
	if x != nil {
		return x.N
	}
	return 0
}

var File_blockio_gcp_proto protoreflect.FileDescriptor

const file_blockio_gcp_proto_rawDesc = "" +
	"\n" +
	"\x11blockio/gcp.proto\x12\ablockio\"3\n" +
	"\tCreateReq\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\"%\n" +
	"\tCreateRes\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"J\n" +
	"\bWriteReq\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"2\n" +
	"\bWriteRes\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\f\n" +
	"\x01n\x18\x02 \x01(\x05R\x01n2i\n" +
	"\x06Copier\x120\n" +
	"\x06Create\x12\x12.blockio.CreateReq\x1a\x12.blockio.CreateRes\x12-\n" +
	"\x05Write\x12\x11.blockio.WriteReq\x1a\x11.blockio.WriteResB\vZ\t./blockiob\x06proto3"

var (
	file_blockio_gcp_proto_rawDescOnce sync.Once
	file_blockio_gcp_proto_rawDescData []byte
)

func file_blockio_gcp_proto_rawDescGZIP() []byte {
	file_blockio_gcp_proto_rawDescOnce.Do(func() {
		file_blockio_gcp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blockio_gcp_proto_rawDesc), len(file_blockio_gcp_proto_rawDesc)))
	})
	return file_blockio_gcp_proto_rawDescData
}

var file_blockio_gcp_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_blockio_gcp_proto_goTypes = []any{
	(*CreateReq)(nil), // 0: blockio.CreateReq
	(*CreateRes)(nil), // 1: blockio.CreateRes
	(*WriteReq)(nil),  // 2: blockio.WriteReq
	(*WriteRes)(nil),  // 3: blockio.WriteRes
}
var file_blockio_gcp_proto_depIdxs = []int32{
	0, // 0: blockio.Copier.Create:input_type -> blockio.CreateReq
	2, // 1: blockio.Copier.Write:input_type -> blockio.WriteReq
	1, // 2: blockio.Copier.Create:output_type -> blockio.CreateRes
	3, // 3: blockio.Copier.Write:output_type -> blockio.WriteRes
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_blockio_gcp_proto_init() }
func file_blockio_gcp_proto_init() {
	if File_blockio_gcp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blockio_gcp_proto_rawDesc), len(file_blockio_gcp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blockio_gcp_proto_goTypes,
		DependencyIndexes: file_blockio_gcp_proto_depIdxs,
		MessageInfos:      file_blockio_gcp_proto_msgTypes,
	}.Build()
	File_blockio_gcp_proto = out.File
	file_blockio_gcp_proto_goTypes = nil
	file_blockio_gcp_proto_depIdxs = nil
}
