// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: blockio/gcp.proto

package blockio

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReq) Reset() {
	*x = CreateReq{}
	mi := &file_blockio_gcp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReq) ProtoMessage() {}

func (x *CreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_blockio_gcp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReq.ProtoReflect.Descriptor instead.
func (*CreateReq) Descriptor() ([]byte, []int) {
	return file_blockio_gcp_proto_rawDescGZIP(), []int{0}
}

func (x *CreateReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type CreateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRes) Reset() {
	*x = CreateRes{}
	mi := &file_blockio_gcp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRes) ProtoMessage() {}

func (x *CreateRes) ProtoReflect() protoreflect.Message {
	mi := &file_blockio_gcp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRes.ProtoReflect.Descriptor instead.
func (*CreateRes) Descriptor() ([]byte, []int) {
	return file_blockio_gcp_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_blockio_gcp_proto protoreflect.FileDescriptor

const file_blockio_gcp_proto_rawDesc = "" +
	"\n" +
	"\x11blockio/gcp.proto\x12\ablockio\"\x1f\n" +
	"\tCreateReq\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"%\n" +
	"\tCreateRes\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2:\n" +
	"\x06Copier\x120\n" +
	"\x06Create\x12\x12.blockio.CreateReq\x1a\x12.blockio.CreateResB\vZ\t./blockiob\x06proto3"

var (
	file_blockio_gcp_proto_rawDescOnce sync.Once
	file_blockio_gcp_proto_rawDescData []byte
)

func file_blockio_gcp_proto_rawDescGZIP() []byte {
	file_blockio_gcp_proto_rawDescOnce.Do(func() {
		file_blockio_gcp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blockio_gcp_proto_rawDesc), len(file_blockio_gcp_proto_rawDesc)))
	})
	return file_blockio_gcp_proto_rawDescData
}

var file_blockio_gcp_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_blockio_gcp_proto_goTypes = []any{
	(*CreateReq)(nil), // 0: blockio.CreateReq
	(*CreateRes)(nil), // 1: blockio.CreateRes
}
var file_blockio_gcp_proto_depIdxs = []int32{
	0, // 0: blockio.Copier.Create:input_type -> blockio.CreateReq
	1, // 1: blockio.Copier.Create:output_type -> blockio.CreateRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_blockio_gcp_proto_init() }
func file_blockio_gcp_proto_init() {
	if File_blockio_gcp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blockio_gcp_proto_rawDesc), len(file_blockio_gcp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blockio_gcp_proto_goTypes,
		DependencyIndexes: file_blockio_gcp_proto_depIdxs,
		MessageInfos:      file_blockio_gcp_proto_msgTypes,
	}.Build()
	File_blockio_gcp_proto = out.File
	file_blockio_gcp_proto_goTypes = nil
	file_blockio_gcp_proto_depIdxs = nil
}
