// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: blockio/gcp.proto

package blockio

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Copier_Create_FullMethodName = "/blockio.Copier/Create"
	Copier_Write_FullMethodName  = "/blockio.Copier/Write"
)

// CopierClient is the client API for Copier service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CopierClient interface {
	Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*CreateRes, error)
	Write(ctx context.Context, in *WriteReq, opts ...grpc.CallOption) (*WriteRes, error)
}

type copierClient struct {
	cc grpc.ClientConnInterface
}

func NewCopierClient(cc grpc.ClientConnInterface) CopierClient {
	return &copierClient{cc}
}

func (c *copierClient) Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*CreateRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRes)
	err := c.cc.Invoke(ctx, Copier_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *copierClient) Write(ctx context.Context, in *WriteReq, opts ...grpc.CallOption) (*WriteRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteRes)
	err := c.cc.Invoke(ctx, Copier_Write_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CopierServer is the server API for Copier service.
// All implementations must embed UnimplementedCopierServer
// for forward compatibility.
type CopierServer interface {
	Create(context.Context, *CreateReq) (*CreateRes, error)
	Write(context.Context, *WriteReq) (*WriteRes, error)
	mustEmbedUnimplementedCopierServer()
}

// UnimplementedCopierServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCopierServer struct{}

func (UnimplementedCopierServer) Create(context.Context, *CreateReq) (*CreateRes, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedCopierServer) Write(context.Context, *WriteReq) (*WriteRes, error) {
	return nil, status.Error(codes.Unimplemented, "method Write not implemented")
}
func (UnimplementedCopierServer) mustEmbedUnimplementedCopierServer() {}
func (UnimplementedCopierServer) testEmbeddedByValue()                {}

// UnsafeCopierServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CopierServer will
// result in compilation errors.
type UnsafeCopierServer interface {
	mustEmbedUnimplementedCopierServer()
}

func RegisterCopierServer(s grpc.ServiceRegistrar, srv CopierServer) {
	// If the following call panics, it indicates UnimplementedCopierServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Copier_ServiceDesc, srv)
}

func _Copier_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CopierServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Copier_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CopierServer).Create(ctx, req.(*CreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Copier_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CopierServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Copier_Write_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CopierServer).Write(ctx, req.(*WriteReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Copier_ServiceDesc is the grpc.ServiceDesc for Copier service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Copier_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blockio.Copier",
	HandlerType: (*CopierServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Copier_Create_Handler,
		},
		{
			MethodName: "Write",
			Handler:    _Copier_Write_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blockio/gcp.proto",
}
